/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MeRouteImport } from './routes/me'
import { Route as CookbooksRouteImport } from './routes/cookbooks'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiResumeChatRouteImport } from './routes/api.resume-chat'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbooksRoute = CookbooksRouteImport.update({
  id: '/cookbooks',
  path: '/cookbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeChatRoute = ApiResumeChatRouteImport.update({
  id: '/api/resume-chat',
  path: '/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/bookmarks': typeof BookmarksRoute
  '/cookbooks': typeof CookbooksRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/uses': typeof UsesRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/bookmarks': typeof BookmarksRoute
  '/cookbooks': typeof CookbooksRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/uses': typeof UsesRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/bookmarks': typeof BookmarksRoute
  '/cookbooks': typeof CookbooksRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/uses': typeof UsesRoute
  '/api/resume-chat': typeof ApiResumeChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/bookmarks'
    | '/cookbooks'
    | '/me'
    | '/projects'
    | '/uses'
    | '/api/resume-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/bookmarks'
    | '/cookbooks'
    | '/me'
    | '/projects'
    | '/uses'
    | '/api/resume-chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/bookmarks'
    | '/cookbooks'
    | '/me'
    | '/projects'
    | '/uses'
    | '/api/resume-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  BookmarksRoute: typeof BookmarksRoute
  CookbooksRoute: typeof CookbooksRoute
  MeRoute: typeof MeRoute
  ProjectsRoute: typeof ProjectsRoute
  UsesRoute: typeof UsesRoute
  ApiResumeChatRoute: typeof ApiResumeChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbooks': {
      id: '/cookbooks'
      path: '/cookbooks'
      fullPath: '/cookbooks'
      preLoaderRoute: typeof CookbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-chat': {
      id: '/api/resume-chat'
      path: '/api/resume-chat'
      fullPath: '/api/resume-chat'
      preLoaderRoute: typeof ApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  BookmarksRoute: BookmarksRoute,
  CookbooksRoute: CookbooksRoute,
  MeRoute: MeRoute,
  ProjectsRoute: ProjectsRoute,
  UsesRoute: UsesRoute,
  ApiResumeChatRoute: ApiResumeChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
